### ISSUE TITLE
some questions about drake

### ISSUE THREAD

**Issue by zapplelove** [guzhaoyuan/drake-tutorial#3]
1. Can it be used to simulate a closed chain robot？
2. As far as I know，the "rbdl" can be used to calculate the Inverse dynamics of robot even if the robot has a closed chain, but it uses the "Baumgarte stabilization" which is beyond my knowledge, can drake solve this?
3. If I use cmake, I'd known that use "make install" command to install into the system but if I use "./install /usr/local" when use bazel, It can't find some files.

**Comment by guzhaoyuan** [comment]
For 1, I believe the answer is yes. Though Drake does not support closed-loop kinematic chains, there's a way to "approximate" one. The [four-bar linkage demo](https://github.com/RobotLocomotion/drake/blob/master/examples/multibody/four_bar/README.md) shows how to close an open chain using "bushing".
For 2, I don't think Drake supports closed chain in general, so no inverse dynamics yet.
For 3, CMake is outside the scope of this tutorial. Drake can be compiled using CMake. But if you want to use the binary version of Drake, you can install the binary rather than compiling using CMake.
